project:
  type: book
  output-dir: docs

book:
  title: "『カテゴリカルデータの連関モデル』"
  author: "藤原翔（東京大学社会科学研究所）"
  date: last-modified
  chapters:
    - index.qmd
    - 1-Introduction.qmd
    - 2-Chapter_1.qmd
    - 3-Chapter_2.qmd
    - 4-Chapter_3.qmd
    - 5-Chapter_4.qmd
    - 6-Chapter_5.qmd
    - 7-Chapter_6.qmd
    - 8-degrees_of_freedom.qmd
    - 9-Note.qmd
    - 10-R.qmd
    - 11-Replication.qmd
    - 12-Review.qmd
    - 13-Crosstabs.qmd
    # - 14-Bayes.qmd  # 未公開
    - 16-LEM.qmd

execute:
  warning: false
  message: false

format:
  html:
    theme: minty
    toc-title: 目次
    code-fold: false
    code-tools: true
    code-block-bg: true
    code-block-border-left: "#0ABAB5"
    link-external-icon: true

bibliography: "/Users/sf/Dropbox/Zjournal/My Library.bib"

crossref:
  fig-title: 図     # (default is "Figure")
  tbl-title: 表     # (default is "Table")
  title-delim: "："     # (default is ":")